export const APPLICATIONS = [
  {
    name: "Avinash kumar Jha",
    role: "PHP Developer",
    workStatus: "Open To Work",
    experience: "3 years",
    currentLocation: "Pune",
    currentCTC: 60000,
    noticePeriod: "30 days",
    skillsMatched: 75,
  },
  {
    name: "Avinash kumar Jha",
    role: "PHP Developerr",
    workStatus: "Open To Work",
    experience: "3 years",
    currentLocation: "Pune",
    currentCTC: 60000,
    noticePeriod: "30 days",
    skillsMatched: 75,
  },
  {
    name: "Avinash kumar Jha",
    role: "PHP Developer",
    workStatus: "Open To Work",
    experience: "3 years",
    currentLocation: "Pune",
    currentCTC: 60000,
    noticePeriod: "30 days",
    skillsMatched: 75,
  },
  {
    name: "Avinash kumar Jha",
    role: "PHP Developer",
    workStatus: "Open To Work",
    experience: "3 years",
    currentLocation: "Pune",
    currentCTC: 60000,
    noticePeriod: "30 days",
    skillsMatched: 75,
  },
];
